### ISSUE TITLE
Add ListItem Details

### ISSUE THREAD

**Issue by Mistobaan** [aivscovid19/search-ui#12]
These features should be aligned with #8 
- [ ] Authors
- [ ] Tags
- [ ] Download link to Article
- [ ] Category ( that Embo? not sure what it is)

I would only add the icons and the description on tooltip, not the actual text.

note: exclude the bookmarking feature as we don't have backend support for that.

![gitscout-image-from-clipboard-1](http://static.gitscout.com/97126286444f95ce3ebaca531c497faa9b1ad9d7e93464980c3a45ec1aba31f6.png)

**Comment by coltonehrman** [comment]
I think this one can be closed since we are going a different direction with the UI
