### ISSUE TITLE
Group navigation does not work on the second level.

### ISSUE THREAD

**Issue by ivankozlovcodes** [aivscovid19/search-ui#16]
Steps to reproduce.
1. Search for any query
2. Navigate to any group.
3. Assert search results in the right column are filtered to the current group.
4. Navigate to any subgroup

Expected: search results are filtered further to match the selected subgroup
Actual: search results are not filtered

**Comment by coltonehrman** [comment]
Fixed with #17

**Comment by coltonehrman** [comment]
I think this one can for sure be closed since it was resolved
