### ISSUE TITLE
Keywords display component.

### ISSUE THREAD

**Issue by ivankozlovcodes** [aivscovid19/search-ui#40]
Add a component to display document keywords in github repo tag style(see the image)

![Screen Shot 2020-08-13 at 6 36 33 PM](https://user-images.githubusercontent.com/17299647/90203453-a1a48200-dd95-11ea-8a0e-5a98479d440c.png)

**Comment by vix993** [comment]
Morning Ivan,

I have prepared a pretty simplistic component to display the keywords.

I wasn't sure about the coloring but I used the header image from https://www.aivscovid19.org/home as reference

![Screen Shot 2020-08-14 at 11 50 39](https://user-images.githubusercontent.com/52217652/90262702-022ed000-de25-11ea-80f4-dddbedde9b75.png)

It can be called it as follows:

![Screen Shot 2020-08-14 at 11 50 50](https://user-images.githubusercontent.com/52217652/90262737-0e1a9200-de25-11ea-83c8-d129315a2069.png)

I am just having issues with visualizing it on the results card, as the server is not responding.

**Comment by dkurgan** [comment]
@vix993 Hey man, login in to slack and i will send you fake data which you can use instead of server
