### ISSUE TITLE
UI Library and Template

### ISSUE THREAD

**Issue by Mistobaan** [aivscovid19/search-ui#6]
I would suggest to use Material ui for the UI templates. material.io is the UI standard created by google.

https://github.com/alexanmtz/material-sense

It has a "medical" look and feel. The library is templatized so we can always upgrade to something more custom down the line. 
![image](https://user-images.githubusercontent.com/112599/82723412-9274d300-9c83-11ea-9d8a-1e661b739a24.png)

**Comment by coltonehrman** [comment]
I think this one can be closed since we already have Material-UI implemented in code base, and we don't need a template
