### ISSUE TITLE
Improve Result List with Expansion Panel

### ISSUE THREAD

**Issue by Mistobaan** [aivscovid19/search-ui#8]
- [ ] Title, authors
- [ ] Hide the abstracts inside the expansion
- [ ] Mock/plan for the checkbox selection (this is for another feature)
- [ ] there is more info that could be displayed (i.e. Keywords but didn't have the time to think through, feel free to experiment and propose) 

component:
- https://material-ui.com/components/expansion-panels/

Mock UI:
![image](https://user-images.githubusercontent.com/112599/83954294-d37cf380-a7fc-11ea-9810-3dc3beda30aa.png)

**Comment by coltonehrman** [comment]
I think this one can be closed since we are going a different direction with the UI
